# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nthu-326/Desktop/1232/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_CY_back_walk_R/BM_CY_back_walk_R.xci
# IP: The module: 'BM_CY_back_walk_R' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nthu-326/Desktop/1232/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_CY_back_walk_R/BM_CY_back_walk_R_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BM_CY_back_walk_R'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/nthu-326/Desktop/1232/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_CY_back_walk_R/BM_CY_back_walk_R.xci
# IP: The module: 'BM_CY_back_walk_R' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nthu-326/Desktop/1232/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_CY_back_walk_R/BM_CY_back_walk_R_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BM_CY_back_walk_R'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
