# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_wooden_fpga_up/BM_wooden_fpga_up.xci
# IP: The module: 'BM_wooden_fpga_up' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_wooden_fpga_up/BM_wooden_fpga_up_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BM_wooden_fpga_up'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_wooden_fpga_up/BM_wooden_fpga_up.xci
# IP: The module: 'BM_wooden_fpga_up' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_wooden_fpga_up/BM_wooden_fpga_up_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BM_wooden_fpga_up'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
