# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/nthu-326/Desktop/1232/Legend of Chun-Yi Lee/cons.xdc

# IP: ip/BM_CS_student_1/BM_CS_student.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BM_CS_student || ORIG_REF_NAME==BM_CS_student} -quiet] -quiet

# IP: ip/BM_CY_front_stand_1/BM_CY_front_stand.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BM_CY_front_stand || ORIG_REF_NAME==BM_CY_front_stand} -quiet] -quiet
