# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_0/BM_0.xci
# IP: The module: 'BM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_0/BM_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BM_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_0/BM_0.xci
# IP: The module: 'BM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/verilog project/Legend of Chun-Yi Lee/Legend of Chun-Yi Lee.srcs/sources_1/ip/BM_0/BM_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BM_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
